export const colors = {
  background: "#111318",
  surface: "#1a1b21",
  surfaceHigh: "#1e2025",
  surfaceHighest: "#282a2f",
  accent: "#4ADE80",
  accentDim: "rgba(74, 222, 128, 0.1)",
  accentBorder: "rgba(74, 222, 128, 0.2)",
  textPrimary: "#e2e2e9",
  textMuted: "rgba(188, 202, 187, 0.6)",
  textDim: "rgba(188, 202, 187, 0.3)",
  border: "rgba(255, 255, 255, 0.06)",
  borderAccent: "rgba(74, 222, 128, 0.3)",
  errorText: "#ff6b6b",
  buttonText: "#0a0a0a",
};

export const fonts = {
  mono: '"JetBrains Mono", "Fira Code", monospace',
  sans: '"Inter", sans-serif',
  label: '"Space Grotesk", sans-serif',
};

export const buttons = {
  primary: {
    backgroundColor: "#4ADE80",
    color: "#0a0a0a",
    fontFamily: '"Space Grotesk", sans-serif',
    fontWeight: 700,
    fontSize: "0.875rem",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    borderRadius: "2px",
    height: "48px",
    border: "none",
    cursor: "pointer",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  secondary: {
    backgroundColor: "transparent",
    color: "#4ADE80",
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 500,
    fontSize: "0.75rem",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    borderRadius: "2px",
    height: "48px",
    border: "1px solid rgba(74, 222, 128, 0.3)",
    cursor: "pointer",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  ghost: {
    backgroundColor: "transparent",
    color: "#e2e2e9",
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 400,
    fontSize: "0.75rem",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    borderRadius: "2px",
    height: "48px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    cursor: "pointer",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
};

export const cards = {
  default: {
    backgroundColor: "#1a1b21",
    border: "1px solid rgba(255, 255, 255, 0.06)",
    borderRadius: "4px",
  },
  accent: {
    backgroundColor: "#1a1b21",
    border: "1px solid rgba(74, 222, 128, 0.2)",
    borderRadius: "4px",
    boxShadow: "0 0 40px -10px rgba(74, 222, 128, 0.15)",
  },
};

export const inputs = {
  default: {
    backgroundColor: "#0c0e13",
    border: "none",
    outline: "none",
    boxShadow: "0 0 0 1px rgba(134, 148, 134, 0.2)",
    color: "#e2e2e9",
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: "0.875rem",
    borderRadius: "2px",
    height: "44px",
    padding: "0 16px",
    width: "100%",
  },
};

export const wordmark = {
  container: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  icon: {
    backgroundColor: "#1a1b21",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "8px",
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: "0.7rem",
    color: "#4ADE80",
  },
  text: {
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "white",
    letterSpacing: "-0.02em",
  },
  accent: {
    color: "#4ADE80",
  },
};
